In [18]:
def mapping_to_actual_data(dataframe_clustered,dataframe_actual,label_to_transfer):
    #dataframe_actual[label_to_transfer]=np.zeros((len(dataframe_actual)),dtype=int)
    list_df=[]
    for index,row in tqdm(dataframe_clustered.iterrows(),total=len(dataframe_clustered)):
        for ele in row['repeated messages']:
            #dataframe_actual.iloc[ele][label_to_transfer]=row[label_to_transfer]
            list_df.append((ele,row[label_to_transfer]))
            
    list_df.sort(key=lambda tup: tup[0])
    print(list_df[0:5])
    list_temp=[ele[1] for ele in list_df]
    dataframe_actual[label_to_transfer]=list_temp
    return dataframe_actual

In [5]:
total_data_to_annnotate['pred_label']=list(np.ones((len(total_data_to_annnotate)),dtype=int))

In [6]:
total_data_to_annnotate.head(5)

,repeated messages,three annotator,text,keywords_count,translated,pred_label
id,,,,,,
1,[216814],"[319b41df-41e6-40e9-a0b4-5cc1b5baf290, d736cba...",‡∞µ‡±Ä‡∞∞‡∞∂‡±à‡∞µ ‡∞≤‡∞ø‡∞Ç‡∞ó‡∞æ‡∞Ø‡∞§‡±ç ‡∞≤‡∞®‡±Å ‡∞Æ‡∞∞‡∞ø...,0,Chandrababu Forgetting Veera Siva Lingayats! C...,1
2,[945024],"[c7b9d20e-2c35-4b9c-b380-7cf8cb5f822d, 394490c...",‡∞Ü‡∞π‡±ç‡∞µ‡∞æ‡∞®‡∞Æ‡±Å ‡∞™‡±Ü‡∞¶‡∞®‡∞Ç‡∞¶‡∞ø‡∞™‡∞æ‡∞°‡±Å ‡∞ú‡∞ø‡∞≤‡±ç‡∞≤‡∞æ ‡∞™...,0,NTR Sports Development Center (Indoor Stadium)...,1
3,[275899],"[cb49c64f-aec9-4d19-91a5-0168058d6cea, 910caaa...",‡∞Æ‡±Å‡∞ñ‡±ç‡∞Ø ‡∞ó‡∞Æ‡∞®‡∞ø‡∞ï ‡∞ú‡∞®‡∞∏‡±á‡∞® ‡∞™‡∞æ‡∞∞‡±ç‡∞ü‡±Ä ‡∞Ö‡∞≠‡±ç‡∞Ø‡∞∞‡±ç...,0,IMPORTANT NOTE: The candidates for the Janasen...,1
4,[112639],"[5411f849-2c32-4bf9-9c0c-b2369963d34f, 0131ef1...",( Updated on 01 - 12 - 2018) ‡¥®‡¥Æ‡¥∏‡µç...,0,"(Updated on 01 - 12 - 2018) Namaste, Janmabhoo...",1
5,[141987],"[8a398de0-b259-49ab-9932-0d5aee2ccc6a, d2281b6...",( Updated on 14 - 12 - 2018) ‡¥®‡¥Æ‡¥∏‡µç...,0,NaN,1

In [19]:
temp=mapping_to_actual_data(total_data_to_annnotate,actual_data,'pred_label')

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 975989/975989 [01:13<00:00, 13196.54it/s]

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1)]

In [15]:
temp.head(5)

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1,group_id_anonymized,lang,message_text,phone_num_anonymized,timestamp,translated,pred_label
0,0,0,0,4.0,4.0,577,hi,*‡§≤‡§ò‡•Å ‡§∏‡§ø‡§Ç‡§ö‡§æ‡§à* ‡§®‡§ø‡§É‡§∂‡•Å‡§≤‡•ç‡§ï ‡§¨‡•ã‡§∞‡§ø‡§Ç‡§ó ‡§Ø‡•ã‡§ú‡§®‡§æ ‡§π‡•á‡§§‡•Å 55 ‡§ï‡§∞...,178320,1549559608000,* Provision of Rs. 55 crore for minor irrigati...,1
1,1,1,1,9.0,9.0,2037,hi,*üì∞FR62* *üëâ‡§¶‡§ø‡§≤‡•ç‡§≤‡•Ä-‡§è‡§®‡§∏‡•Ä‡§Ü‡§∞ ‡§Æ‡•á‡§Ç ‡§∂‡§ø‡§Æ‡§≤‡§æ ‡§ú‡•à‡§∏‡•Ä ‡§¨‡§∞‡•ç‡§´‡§¨‡§æ‡§∞...,39877,1549559738000,* üì∞ üì∞FR62 üëâ * * Shimla-like snowfall in Delh...,1
2,2,2,2,10.0,10.0,3634,hi,‡§ï‡§≤ ‡§Æ‡•à‡§®‡•á ‡§è‡§ï ‡§Ü‡§¶‡§Æ‡•Ä ‡§∏‡•á ‡§≤‡§ø‡§´‡•ç‡§ü ‡§Æ‡§æ‡§Å‡§ó‡§æ ‡§â‡§∏‡§ï‡•á ‡§¨‡§æ‡§¶ ‡§ß‡§®‡•ç‡§Ø‡§µ‡§æ...,198635,1549559843000,"Yesterday I asked for a lift from a man, after...",1
3,3,3,3,11.0,11.0,2284,hi,‡§ï‡§≤ ‡§Æ‡•à‡§®‡•á ‡§è‡§ï ‡§Ü‡§¶‡§Æ‡•Ä ‡§∏‡•á ‡§≤‡§ø‡§´‡•ç‡§ü ‡§Æ‡§æ‡§Å‡§ó‡§æ ‡§â‡§∏‡§ï‡•á ‡§¨‡§æ‡§¶ ‡§ß‡§®‡•ç‡§Ø‡§µ‡§æ...,198635,1549559851000,"Yesterday I asked for a lift from a man, after...",1
4,4,4,4,13.0,13.0,3700,te,‡∞∏‡∞∞‡±ç‡∞µ‡±á‡∞≤‡±Å ‡∞∏‡±Ç‡∞∏‡∞ø ‡∞Æ‡±Å‡∞∞‡∞ø‡∞∏‡∞ø ‡∞™‡±ã‡∞µ‡∞¶‡±ç‡∞¶‡±Å ‡∞Æ‡∞ø‡∞§‡±ç‡∞∞‡±Å‡∞≤‡±Å ‡∞¨‡∞æ‡∞¨‡±Å ‡∞ú‡∞ø‡∞§‡±ç...,153553,1549559896000,Surveys Don't Surprise Friends,1